### PR TITLE
Update deprecated beanie config and add UnitTests

### PR DESCRIPTION
**Pull request by quniv**
This PR add test for PR #13 , and update Collection deprecated config
- Add: UnitTest & Mock authentication for testing follow by officical FastAPI support
- Fix: the application cannot start up due to the deprecated config setting in the Collection settings.
- Update: edit README.md to provide clearer instructions on how to start.
- Update: use newest version for packages

### CODE REVIEW

**Comment by Youngestdev** [comment]
Thank you for raising this PR, @qitpy! I will review it later this week.

**Comment by quniv** [comment]
i will add the mock of the database in the next PR

**Comment by Youngestdev** [comment]
Thank you for this, @qitpy! I will review this and get back ASAP!

**Review by Youngestdev — APPROVED** [review]
LGTM! Thank you, @qitpy !

**Pull request merged**
